name: app
description: Editor App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6 # 22.12.03.
  flutter_secure_storage: ^6.1.0 # 22.12.03.
  json_annotation: ^4.7.0 # 22.12.03.
  retrofit: ^3.3.1 # 22.12.03.
  logger: any # retrofit 부과
  flutter_riverpod: ^2.1.1 # 22.12.03.
  go_router: ^5.2.1 # 22.12.03.
  uuid: ^3.0.7 # 22.12.03.
  debounce_throttle: ^2.0.0 # 22.12.03.
  badges: ^2.0.3 # 22.12.03.
  shared_preferences: ^2.0.15 # 22.12.03.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0' # retrofit
  build_runner: '>2.3.0 <4.0.0' #retrofit
  json_serializable: '>4.4.0' #retrofit

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 600
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100